name: daily-ig-post

on:
  # Only trigger the workflow when a new comment is created and it contains the phrase "run daily-ig-post"
  issue_comment:
    types: [created]
    contains: "run daily-ig-post"

jobs:
  post-to-instagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        working-directory: ./scripts
        run: npm install
      - name: Compile TypeScript for post-to-instagram script
        working-directory: ./scripts
        run: npm run build:post-to-instagram
      - name: Run post-to-instagram script
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          NAKEDEXTRACRISPY_AUTH_KEY: ${{ secrets.NAKEDEXTRACRISPY_AUTH_KEY }}
        working-directory: ./scripts
        run: |
          node dist/post-to-instagram.js
